# Generated by Django 4.2.23 on 2024-08-25 22:49

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import F





class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [

 

        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        

    
    ]
