# Generated by Django 4.2.23 on 2024-08-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_vendedores_produtos_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='nome',
            field=models.CharField(default='vendedor', max_length=40),
        ),
    ]
