# Generated by Django 4.2.23 on 2024-08-25 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    
    
    dependencies = [
        ('apis', '0003_vendedores_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.vendedores'),
        ),

    

    ]
