# Generated by Django 4.2.23 on 2024-08-25 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_produtos_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.vendedores'),
        ),
        migrations.AlterField(
            model_name='vendedores',
            name='nome',
            field=models.CharField(max_length=40),
        ),
    ]
