# Generated by Django 4.2.23 on 2024-08-26 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_produtos_vendedor_alter_vendedores_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='vendedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='apis.vendedores'),
        ),
    ]
