# Generated by Django 4.2.23 on 2024-08-26 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_produtos_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.vendedores'),
        ),
    ]
